# Computation with multiple methods

In [1]:
import numpy as np

Upload the `data.csv` file to this workspace, then read in the data to a `numpy` array in `x`. If you want to, you can add code to the following cell to explore `x` (for example, see its shape).


In [2]:
x = np.genfromtxt('data.csv',delimiter=',')
x

array([[48., 57., 71., 58., 75., 90., 71., 92., 76., 73., 54., 63., 88.,
        65., 81.],
       [57., 60., 55., 79., 94., 72., 66., 89., 61., 53., 63., 66., 67.,
        57., 68.],
       [63., 76., 48., 63., 85., 88., 68., 92., 81., 59., 47., 59., 69.,
        75., 53.],
       [51., 59., 49., 54., 85., 95., 96., 89., 75., 86., 55., 73., 68.,
        42., 60.],
       [82., 56., 67., 82., 93., 86., 60., 72., 83., 51., 81., 81., 86.,
        68., 79.],
       [63., 61., 47., 49., 94., 95., 96., 77., 80., 62., 54., 89., 93.,
        47., 60.],
       [59., 73., 45., 84., 93., 94., 57., 64., 61., 75., 44., 61., 66.,
        52., 55.],
       [72., 90., 71., 64., 86., 82., 89., 72., 65., 52., 66., 59., 58.,
        56., 76.],
       [58., 72., 62., 62., 78., 69., 76., 88., 55., 70., 69., 90., 64.,
        77., 82.],
       [50., 70., 64., 77., 89., 63., 79., 65., 69., 64., 73., 91., 87.,
        65., 72.],
       [87., 84., 74., 64., 61., 79., 78., 77., 79., 76., 74., 70., 86.,
       

Write code to compute the following arrays:

* `grades_all_methods` - student grades according to each of the four different methods (first column: Method A, second column: Method B, third column: Method C, fourth column: method D).
* `grades` - student grades using "best of four methods".
* `idx_method` - the index of the grading method that realizes the highest grade for each student (0 for Method A, 1 for Method B, 2 for Method C, and 3 for Method D).

In [9]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
lab = x[:,:5]
pro_set = x[:,5:13]
mid = x[:,-2]
final = x[:,-1]

avg_lab = np.mean(lab, axis=1)
avg_problem_set = np.mean(pro_set, axis=1)

# Compute grades using the four methods
grades_A = 0.25 * avg_lab + 0.25 * avg_problem_set + 0.25 * mid + 0.25 * final
grades_B = 0.20 * avg_lab + 0.20 * avg_problem_set + 0.30 * mid + 0.30 * final
grades_C = 0.30 * avg_lab + 0.30 * avg_problem_set + 0.20 * mid + 0.20 * final
grades_D = 0.20 * avg_lab + 0.20 * avg_problem_set + 0.20 * mid + 0.40 * final

# Stack grades from all methods
grades_all_methods = np.column_stack((grades_A, grades_B, grades_C, grades_D))

# Compute best grade and index of the method
grades = np.max(grades_all_methods, axis=1)
idx_method = np.argmax(grades_all_methods, axis=1)


You can test your work by looking at the output in the next cells (which you can also modify as you like - these cells will not be graded):

In [11]:
grades_all_methods

array([[70.91875, 71.335  , 70.5025 , 72.935  ],
       [65.28125, 64.725  , 65.8375 , 65.825  ],
       [66.34375, 65.875  , 66.8125 , 63.675  ],
       [60.30625, 58.445  , 62.1675 , 60.245  ],
       [74.5    , 74.3    , 74.7    , 75.4    ],
       [62.6375 , 60.81   , 64.465  , 62.11   ],
       [60.7625 , 59.31   , 62.215  , 59.61   ],
       [69.11875, 68.495  , 69.7425 , 70.495  ],
       [74.50625, 75.505  , 73.5075 , 76.005  ],
       [70.21875, 69.875  , 70.5625 , 70.575  ],
       [75.84375, 75.875  , 75.8125 , 76.075  ],
       [68.2375 , 68.49   , 67.985  , 66.19   ],
       [71.36875, 71.995  , 70.7425 , 71.295  ],
       [60.13125, 58.305  , 61.9575 , 59.705  ],
       [77.8875 , 79.01   , 76.765  , 79.51   ],
       [70.6625 , 69.93   , 71.395  , 69.93   ],
       [72.075  , 73.06   , 71.09   , 73.46   ],
       [73.4625 , 74.87   , 72.055  , 75.57   ],
       [68.95625, 68.265  , 69.6475 , 67.965  ],
       [64.4    , 62.82   , 65.98   , 61.72   ],
       [72.95   , 72

In [12]:
grades

array([72.935 , 65.8375, 66.8125, 62.1675, 75.4   , 64.465 , 62.215 ,
       70.495 , 76.005 , 70.575 , 76.075 , 68.49  , 71.995 , 61.9575,
       79.51  , 71.395 , 73.46  , 75.57  , 69.6475, 65.98  , 73.74  ,
       68.555 , 65.55  , 69.655 , 67.255 , 63.77  , 73.77  , 68.37  ,
       72.745 , 70.73  , 64.8725, 75.885 , 76.94  , 64.4975, 66.135 ,
       73.86  , 72.73  , 68.15  , 72.715 , 69.42  , 70.715 , 67.635 ])

In [13]:
idx_method

array([3, 2, 2, 2, 3, 2, 2, 3, 3, 3, 3, 1, 1, 2, 3, 2, 3, 3, 2, 2, 2, 1,
       3, 1, 2, 3, 1, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 3, 1, 2, 3])